//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewWpfDev.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Data Source=DINO-PC;Initial Catalog=""C:\USERS\IANCH\APPDATA\LOCAL\MICROSOFT\MICROSOFT SQL SERVER LOCAL DB\INSTANCES\MSSQLLOCALDB\IAN1.MDF"";Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False")]
        public string xBankSysConnectionString {
            get {
                return ((string)(this["xBankSysConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DINO-PC;Initial Catalog=Northwind;Integrated Security=True;Connect Ti" +
            "meout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;" +
            "MultiSubnetFailover=False")]
        public string NorthwindConnectionString {
            get {
                return ((string)(this["NorthwindConnectionString"]));
            }
            set {
                this["NorthwindConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DINO-PC;Initial Catalog=\"IAN1\";Integrated Security=True;Connect Timeo" +
            "ut=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;Mul" +
            "tiSubnetFailover=False")]
        public string NewBanksys {
            get {
                return ((string)(this["NewBanksys"]));
            }
            set {
                this["NewBanksys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DINO-PC;Initial Catalog=\"IAN1\";Integrated Security=True;Connect Timeo" +
            "ut=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;Mul" +
            "tiSubnetFailover=False")]
        public string BankSysConnectionString {
            get {
                return ((string)(this["BankSysConnectionString"]));
            }
            set {
                this["BankSysConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DINO-PC;Initial Catalog=\"ADVENTUREWORKS2019\";Integrated Security=True" +
            ";Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent" +
            "=ReadWrite;MultiSubnetFailover=False")]
        public string AdventureWorks2019 {
            get {
                return ((string)(this["AdventureWorks2019"]));
            }
            set {
                this["AdventureWorks2019"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DINO-PC;Initial Catalog=\"PUBS\";Integrated Security=True;Connect Timeo" +
            "ut=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;Mul" +
            "tiSubnetFailover=False")]
        public string PubsConnectionString {
            get {
                return ((string)(this["PubsConnectionString"]));
            }
            set {
                this["PubsConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TRUE")]
        public string UseScrollViewer {
            get {
                return ((string)(this["UseScrollViewer"]));
            }
            set {
                this["UseScrollViewer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TRUE")]
        public string ReplaceFldNames {
            get {
                return ((string)(this["ReplaceFldNames"]));
            }
            set {
                this["ReplaceFldNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TRUE")]
        public string UseFlowDoc {
            get {
                return ((string)(this["UseFlowDoc"]));
            }
            set {
                this["UseFlowDoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseMagnify {
            get {
                return ((bool)(this["UseMagnify"]));
            }
            set {
                this["UseMagnify"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W:\\\\NewWpfDev\\\\bin\\\\Debug\\\\")]
        public string AppRootPath {
            get {
                return ((string)(this["AppRootPath"]));
            }
            set {
                this["AppRootPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FlowDocFont {
            get {
                return ((string)(this["FlowDocFont"]));
            }
            set {
                this["FlowDocFont"] = value;
            }
        }
    }
}
